# Generated by Django 3.1.7 on 2021-03-25 19:45

from django.db import migrations, models
import django.db.models.aggregates
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='dealers.dealer'),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_tank_capacity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], default='Petrol', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='car',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='car',
            name='image4',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='car',
            name='kilometers',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='car',
            name='power',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name=django.db.models.aggregates.Min(1000)),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.IntegerField(default=123456, verbose_name=django.db.models.aggregates.Min(11)),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], default=2021, verbose_name='year'),
        ),
    ]
